### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by lcGit0615** [smallsnail-wh/wh-web#3]
当运行npm run init命令时，报如下错误：
> wh-web@1.0.0 init D:\vue\wh-web
> webpack --progress --config webpack.dev.config.js

  0% compilingfs.js:157
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:157:9)
    at Object.fs.write (fs.js:674:14)
    at D:\vue\wh-web\webpack.dev.config.js:10:8
    at FSReqWrap.oncomplete (fs.js:169:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wh-web@1.0.0 init: `webpack --progress --config webpack.dev.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wh-web@1.0.0 init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\刘超\AppData\Roaming\npm-cache\_logs\2018-05-30T06_40_55_041Z-debug.log
 
这是什么原因？？？？？？？？？？？？？？

**Comment by smallsnail-wh** [comment]
node.js的版本问题
我这边用的是8.11.2

**Comment by lcGit0615** [comment]
好的、谢谢，我把webpack.dev.config.js开头的fs.write（）那里注释掉就可以了，是不是fs.write方法跟node.js的版本有关系？

**Comment by smallsnail-wh** [comment]
这就有点坑了，我觉得应该不是这个原因，我觉得应该是普通命令没有权限做fs写操作，我这边没有出现这个问题，如果你是mac系统，可以试一下sudo npm，用管理员权限试一下

**Comment by Lisa2015** [comment]
本地运行成功之后登录不了啊?需要注释掉哪些代码

**Comment by smallsnail-wh** [comment]
@Lisa2015 后端服务也需要搭建，wh-server.
